//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRequest
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Department { get; set; }
        public string InvestStatus { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectSummary { get; set; }
        public string StudyArea { get; set; }
        public string ServiceType { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string RequestStatus { get; set; }
        public int ProjectId { get; set; }
        public string Degree { get; set; }
        public string PreferBiostat { get; set; }
    
        public virtual Project Projects { get; set; }
    }
}
