//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClientRequestTracker : DbContext
    {
        public ClientRequestTracker()
            : base("name=ClientRequestTracker")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BioStat_cr> BioStat_cr { get; set; }
        public virtual DbSet<ClientRequest_cr> ClientRequest_cr { get; set; }
        public virtual DbSet<InvestStatus_cr> InvestStatus_cr { get; set; }
        public virtual DbSet<JabsomAffil_cr> JabsomAffil_cr { get; set; }
        public virtual DbSet<ProjectField_cr> ProjectField_cr { get; set; }
        public virtual DbSet<ClientRequest2_cr> ClientRequest2_cr { get; set; }
    }
}
