//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAgmt
    {
        public ClientAgmt()
        {
            this.InvoiceItem2 = new HashSet<InvoiceItem2>();
        }
    
        public int Id { get; set; }
        public int CollabCtrId { get; set; }
        public string ClientRefNum { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<decimal> ApprovedPhdHr { get; set; }
        public Nullable<decimal> ApprovedPhdRate { get; set; }
        public Nullable<decimal> ApprovedMsHr { get; set; }
        public Nullable<decimal> ApprovedMsRate { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public Nullable<System.DateTime> ClientApprovalDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string Comments { get; set; }
        public string Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string FileName { get; set; }
        public byte[] FileUpload { get; set; }
        public string ProjectPhase { get; set; }
        public string AgmtId { get; set; }
        public string AgmtStatus { get; set; }
        public int Project2Id { get; set; }
    
        public virtual CollabCtr CollabCtr { get; set; }
        public virtual ICollection<InvoiceItem2> InvoiceItem2 { get; set; }
        public virtual Project2 Project2 { get; set; }
    }
}
