//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Date1
    {
        public Date1()
        {
            this.TimeEntries = new HashSet<TimeEntry>();
        }
    
        public int DateKey { get; set; }
        public System.DateTime Date { get; set; }
        public string Day { get; set; }
        public Nullable<short> DayOfWeek { get; set; }
        public Nullable<short> DayOfMonth { get; set; }
        public Nullable<short> DayOfYear { get; set; }
        public Nullable<System.DateTime> PreviousDay { get; set; }
        public Nullable<System.DateTime> NextDay { get; set; }
        public Nullable<short> WeekOfYear { get; set; }
        public string Month { get; set; }
        public Nullable<short> MonthOfYear { get; set; }
        public Nullable<short> QuarterOfYear { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual ICollection<TimeEntry> TimeEntries { get; set; }
    }
}
