//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectServiceDetail
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public string ServiceDetail { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Creator { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
