//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectGrant1
    {
        public int Id { get; set; }
        public int GrantAffilId { get; set; }
        public int ProjectId { get; set; }
    
        public virtual GrantAffil GrantAffil { get; set; }
        public virtual Project Project { get; set; }
    }
}
