//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public Publication()
        {
            this.PublicationBioStats = new HashSet<PublicationBioStat>();
            this.PublicationGrants = new HashSet<PublicationGrant>();
            this.PubHistories = new HashSet<PubHistory>();
            this.PublicationCoAuthorAffils = new HashSet<PublicationCoAuthorAffil>();
        }
    
        public int Id { get; set; }
        public int PubType { get; set; }
        public int Status { get; set; }
        public System.DateTime SubmitDate { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public Nullable<System.DateTime> PubDate { get; set; }
        public int JounralId { get; set; }
        public int ConferenceId { get; set; }
        public string Title { get; set; }
        public string Author { get; set; }
        public string Comment { get; set; }
        public int ProjectId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Volume { get; set; }
        public string Issue { get; set; }
        public string Page { get; set; }
        public string DOI { get; set; }
        public string PMID { get; set; }
        public string PMCID { get; set; }
        public Nullable<bool> IsPosterConf { get; set; }
        public Nullable<int> RedcapId { get; set; }
        public string SampleAccept { get; set; }
        public string Affiliation { get; set; }
        public string AffiliationOther { get; set; }
    
        public virtual Conference Conference { get; set; }
        public virtual ICollection<PublicationBioStat> PublicationBioStats { get; set; }
        public virtual ICollection<PublicationGrant> PublicationGrants { get; set; }
        public virtual Journal Journal { get; set; }
        public virtual ICollection<PubHistory> PubHistories { get; set; }
        public virtual ICollection<PublicationCoAuthorAffil> PublicationCoAuthorAffils { get; set; }
        public virtual Project2 Project2 { get; set; }
    }
}
