//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    
    public enum StatusEnum : int
    {
        SubResub = 1,
        Accepted = 2,
        Published = 3,
        NotAccepted = 4
    }
}
