//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewGrant2
    {
        public int Id { get; set; }
        public string PI { get; set; }
        public string Biostat { get; set; }
        public string GrantTitle { get; set; }
        public string GrantStatus { get; set; }
        public string GrantSubmitDate { get; set; }
        public string FundStatus { get; set; }
        public string FundDate { get; set; }
        public string InitDate { get; set; }
        public int ProjectId { get; set; }
        public bool IsInternal { get; set; }
    }
}
