//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBiostatTime
    {
        public int projectid { get; set; }
        public string title { get; set; }
        public int piid { get; set; }
        public string piname { get; set; }
        public int biostatid { get; set; }
        public string lastentry { get; set; }
        public Nullable<int> monthdiff { get; set; }
        public Nullable<bool> IsInternal { get; set; }
    }
}
