//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProjectBiostat
    {
        public int ProjectId { get; set; }
        public int BiostatId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int InvestId { get; set; }
        public string Title { get; set; }
    }
}
